DROP TABLE IF EXISTS ACTOR;
DROP TABLE IF EXISTS MOVIE_CAST;
DROP TABLE IF EXISTS DIRECTOR;
DROP TABLE IF EXISTS MOVIE_DIRECTION;
DROP TABLE IF EXISTS MOVIE;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS MOVIE_GENRES;
DROP TABLE IF EXISTS REVIEWER;
DROP TABLE IF EXISTS RATING;


CREATE TABLE ACTOR(
ACD_ID INTEGER ,
ACD_FNAME CHAR (20),
ACT_LNAME CHAR (20),
ACT_GENDER CHAR(1),
PRIMARY KEY (ACD_ID),
);

CREATE TABLE MOVIE(
MOV_ID  INTEGER ,
MOV_TITLE CHAR (50),
MOV_YEAR INTEGER ,
MOV_TIME INTEGER ,
MOV_LANG CHAR (50),
MOV_DT_REL DATA,
MO_REL_COUNTRY CHAR (5),

PRIMARY KEY (MOV_ID)
);
CREATE TABLE MOVIE_CAST(
ACT_ID INTEGER ,
MOV_ID INTEGER ,
ROLE CHAR (30),

FOREIGN KEY (ACT_ID)REFERENCES ACTOR(ACD_ID),
FOREIGN KEY (MOV_ID)REFERENCES MOVIE(MOV_ID)
);

CREATE TABLE DIRECTOR(
DIR_ID INTEGER,
DIR_FNAME CREATE (20),
DIR_LNAME CHAR (20),

PRIMARY KEY (DIR_ID)
);

CREATE TABLE MOVIE_DIRECTION(
DIR_ID INTEGER ,
MOV_ID INTEGER,

FOREIGN KEY (DIR_ID)REFERENCES  DIRECTOR(DIR_ID)
);


CREATE TABLE GENRES(
GEN_ID INTEGER ,
GEN_TITLE CHAR (20),
PRIMARY KEY (GEN_ID)
);

CREATE TABLE MOVIE_GENRES(
MOV_ID INTEGER,
GEN_ID INTEGER ,

FOREIGN KEY (MOV_ID)REFERENCES MOVIE(MOV_ID),
FOREIGN KEY (GEN_ID)REFERENCES GENRES(GEN_ID)
);

CREATE TABLE REVIEWER(
REV_ID INTEGER ,
REV_NAME CHAR (30),

PRIMARY KEY (REV_ID)
);

CREATE TABLE RATING(
MOV_ID INTEGER ,
REV_ID INTEGER ,
REV_STARS INTEGER ,
NUM_O_RATINGS INTEGER ,

FOREIGN KEY (MOV_ID)REFERENCES MOVIE(MOV_ID),
FOREIGN KEY (REV_ID)REFERENCES REVIEWER(REV_ID)
);