DROP TABLE IF EXISTS MATCH_CAPTAIN;
DROP TABLE IF EXISTS PENALTY_GK;
DROP TABLE IF EXISTS PLAYING_POSITION;

DROP TABLE IF EXISTS PLAYER_MAST;
DROP TABLE IF EXISTS PLAYER_BOOKED;
DROP TABLE IF EXISTS PENALTY_SHOOTOUT;

DROP TABLE IF EXISTS SOCCER_TEAM;
DROP TABLE IF EXISTS SOCCER_COUNTRY;
DROP TABLE IF EXISTS PLAYER_IN_OUT;

DROP TABLE IF EXISTS GOAL_DETAILS;
DROP TABLE IF EXISTS SOCCER_CITY;
DROP TABLE IF EXISTS SOCCER_VENUE;

DROP TABLE IF EXISTS MATCH_MAST;
DROP TABLE IF EXISTS MATCH_DETAILS;
DROP TABLE IF EXISTS ASST_REFEREE_MAST;

DROP TABLE IF EXISTS REFEREE_MAST;
DROP TABLE IF EXISTS COACH_MAST;
DROP TABLE IF EXISTS TEAM_COACHES;

CREATE TABLE PLAYING_POSITION (
  POSITION_ID   NUMERIC,
  POSITION_DESC VARCHAR(15),

  PRIMARY KEY (POSITION_ID)
);

CREATE TABLE COACH_MAST (
  COACH_ID   NUMERIC,
  COACH_NAME VARCHAR(40),

  PRIMARY KEY (COACH_ID)
);

CREATE TABLE SOCCER_TEAM (
  TEAM_ID        NUMERIC,
  TEAM_GROUP     CHARACTER(1),
  MATCH_PLAYED   NUMERIC,
  WON            NUMERIC,
  DRAW           NUMERIC,
  LOST           NUMERIC,
  GOAL_FOR       NUMERIC,
  GOAL_AGNST     NUMERIC,
  GOAL_DIFF      NUMERIC,
  POINTS         NUMERIC,
  GROUP_POSITION NUMERIC,

  PRIMARY KEY (TEAM_ID)
);

CREATE TABLE PLAYER_MAST (
  PLAER_ID     NUMERIC,
  TEAM_ID      NUMERIC,
  JERSEY_NO    NUMERIC,
  PLAER_NAME   VARCHAR(40),
  POSI_TO_PLAY CHARACTER(2),
  DT_OF_BIR    DATE,
  AGE          NUMERIC,
  PLAYING_CLUB VARCHAR(40),

  PRIMARY KEY (PLAER_ID),
  FOREIGN KEY (TEAM_ID) REFERENCES SOCCER_TEAM (TEAM_ID)
);

CREATE TABLE SOCCER_COUNTRY (
  COUNTRY_ID   NUMERIC,
  COUNTRY_ADDR VARCHAR(4),
  COUNTRY_NAME VARCHAR(40),

  PRIMARY KEY (COUNTRY_ID)
);

CREATE TABLE REFEREE_MAST (
  REFEREE_ID   NUMERIC,
  REFEREE_NAME VARCHAR(40),
  COUNTRY_ID   NUMERIC,

  PRIMARY KEY (REFEREE_ID),
  FOREIGN KEY (COUNTRY_ID) REFERENCES SOCCER_COUNTRY (COUNTRY_ID),
);

CREATE TABLE MATCH_MAST (
  MATCH_NO     NUMERIC,
  PLAY_STAGE   CHARACTER(1),
  PLAY_DATE    DATE,
  RESULTS      CHARACTER(5),
  DECIDED_BY   CHARACTER(1),
  GOAL_SCORE   CHARACTER(5),
  VENUE_ID     NUMERIC,
  REFEREE_ID   NUMERIC,
  AUDENCE      NUMERIC,
  PIR_OF_MATCH NUMERIC,
  STOP1_SEC    NUMERIC,
  STOP2_SEC    NUMERIC,

  PRIMARY KEY (MATCH_NO, DECIDED_BY),
  FOREIGN KEY (REFEREE_ID) REFERENCES REFEREE_MAST (REFEREE_ID),
);

CREATE TABLE PLAYER_BOOKED (
  MATCH_NO      NUMERIC,
  TEAM_ID       NUMERIC,
  PLAYER_ID     NUMERIC,
  BOOKING_TIME  VARCHAR(40),
  SENT_OFF      CHARACTER(1),
  PLAY_SCHEDULE CHARACTER(2),
  PLAY_HALF     NUMERIC,

  FOREIGN KEY (TEAM_ID) REFERENCES SOCCER_TEAM (TEAM_ID),
  FOREIGN KEY (MATCH_NO) REFERENCES MATCH_MAST (MATCH_NO),
  FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER_MAST (PLAER_ID),
);

CREATE TABLE PLAYER_IN_OUT (
  MATCH_ON      NUMERIC,
  TEAM_ID       NUMERIC,
  PLAYER_ID     NUMERIC,
  IN_OUT        CHARACTER(1),
  TIME_IN_OUT   NUMERIC,
  PLAY_SCHEDULE CHARACTER(2),
  PLAY_HALF     NUMERIC,

  FOREIGN KEY (MATCH_ON) REFERENCES MATCH_MAST (MATCH_NO),
  FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER_BOOKED (PLAYER_ID),
  FOREIGN KEY (TEAM_ID) REFERENCES SOCCER_TEAM (TEAM_ID)
);

CREATE TABLE MATCH_CAPTAIN (
  MATCH_NO        NUMERIC,
  TEAM_ID         NUMERIC,
  PLAYER_CAPITAIN NUMERIC,

  FOREIGN KEY (MATCH_NO) REFERENCES MATCH_MAST (MATCH_NO),
  FOREIGN KEY (TEAM_ID) REFERENCES SOCCER_TEAM (TEAM_ID),
);

CREATE TABLE PENALTY_GK (
  MATCH_ON  NUMERIC,
  TEAM_ID   NUMERIC,
  PLAYER_GK NUMERIC,

  PRIMARY KEY (PLAYER_GK),
  FOREIGN KEY (MATCH_ON) REFERENCES MATCH_MAST (MATCH_NO),
  FOREIGN KEY (TEAM_ID) REFERENCES SOCCER_TEAM (TEAM_ID),
);

CREATE TABLE PENALTY_SHOOTOUT (
  KICK_ID    NUMERIC,
  MATCH_NO   NUMERIC,
  TEAM_ID    NUMERIC,
  PLAYER_ID  NUMERIC,
  SCORE_GOAL VARCHAR(1),
  KICK_NO    NUMERIC,

  PRIMARY KEY (KICK_ID),

  FOREIGN KEY (MATCH_NO) REFERENCES MATCH_MAST (MATCH_NO),
  FOREIGN KEY (TEAM_ID) REFERENCES SOCCER_TEAM (TEAM_ID),
  FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER_BOOKED (PLAYER_ID)
);

CREATE TABLE TEAM_COACHES (
  TEAM_ID  NUMERIC,
  COACH_ID NUMERIC,

  FOREIGN KEY (TEAM_ID) REFERENCES SOCCER_TEAM (TEAM_ID),
  FOREIGN KEY (COACH_ID) REFERENCES COACH_MAST (COACH_ID),
);

CREATE TABLE GOAL_DETAILS (
  GOAL_ID       NUMERIC,
  MATCH_NO      NUMERIC,
  TEAM_ID       NUMERIC,
  PLAER_ID      NUMERIC,
  GOAL_TIME     NUMERIC,
  GOAL_TYPE     CHARACTER(1),
  PLAY_STAGE    CHARACTER(1),
  GOAL_SCHEDULE CHARACTER(2),
  GOAL_HALF     NUMERIC,

  PRIMARY KEY (GOAL_ID),
  FOREIGN KEY (MATCH_NO) REFERENCES MATCH_MAST (MATCH_NO),
  FOREIGN KEY (TEAM_ID) REFERENCES SOCCER_TEAM (TEAM_ID),
  FOREIGN KEY (PLAER_ID) REFERENCES PLAYER_BOOKED (PLAYER_ID),
);

CREATE TABLE SOCCER_CITY (
  CITY_ID    NUMERIC,
  CITY       VARCHAR(25),
  COUNTRY_ID NUMERIC,

  PRIMARY KEY (CITY_ID),
  FOREIGN KEY (COUNTRY_ID) REFERENCES SOCCER_COUNTRY (COUNTRY_ID),
);

CREATE TABLE SOCCER_VENUE (
  VENUE_ID     NUMERIC,
  VENUE_NAME   VARCHAR(30),
  CITY_ID      NUMERIC,
  AUD_CAPACITY NUMERIC,

  PRIMARY KEY (VENUE_ID),
  FOREIGN KEY (CITY_ID) REFERENCES SOCCER_CITY (CITY_ID)
);

CREATE TABLE MATCH_DETAILS (
  MATCH_NO   NUMERIC,
  PLAY_STAGE VARCHAR(1),
  TEAM_ID    NUMERIC,
  WIN_LOOS   VARCHAR(1),
  DECIDED_BY VARCHAR,
  GOAL_SCORE NUMERIC,
  ASS_REF    NUMERIC,
  PLAEYR_GK  NUMERIC,

  FOREIGN KEY (MATCH_NO) REFERENCES MATCH_MAST (MATCH_NO),
  FOREIGN KEY (TEAM_ID) REFERENCES SOCCER_TEAM (TEAM_ID),
  FOREIGN KEY (PLAEYR_GK) REFERENCES PENALTY_GK (PLAYER_GK),
);

CREATE TABLE ASST_REFEREE_MAST (
  ASS_REF_ID   NUMERIC,
  ASS_REF_NAME VARCHAR(40),
  COUNTRY_ID   NUMERIC,

  PRIMARY KEY (ASS_REF_ID),
  FOREIGN KEY (COUNTRY_ID) REFERENCES SOCCER_COUNTRY (COUNTRY_ID),
);