DROP TABLE IF EXISTS REGIONS;
DROP TABLE IF EXISTS COUNTRIES;
DROP TABLE IF EXISTS LOCATIONS;
DROP TABLE IF EXISTS DEPARTMENTS;
DROP TABLE IF EXISTS JOB_HISTORY;
DROP TABLE IF EXISTS EMPLOYEES;
DROP TABLE IF EXISTS JOBS;
DROP TABLE IF EXISTS JOB_GRADS;


CREATE TABLE REGIONS (
  REGION_ID   NUMBER,
  REGION_NAME varchar(25),

  PRIMARY KEY (REGION_ID)
);

CREATE TABLE COUNTRIES (
  COUNTRY_ID   CHAR(2),
  COUNTRY_NAME varchar(40),
  REGION_ID    NUMBER,

  PRIMARY KEY (COUNTRY_ID),
  FOREIGN KEY (REGION_ID) REFERENCES REGIONS (REGION_ID),
);

CREATE TABLE LOCATIONS (
  LOCATION_ID    NUMBER,
  STREET_ADDRESS VARCHAR(25),
  POSTAL_CODE    VARCHAR(12),
  CITY           VARCHAR(30),
  STATE_PROVINCE VARCHAR(12),
  COUNTRY_ID     CHAR(2),

  PRIMARY KEY (LOCATION_ID),
  FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES (COUNTRY_ID),
);

CREATE TABLE DEPARTMENTS (
  DEPARTNENT_ID   NUMBER,
  DEPARTNENT_NAME VARCHAR(30),
  MANAGER_ID      NUMBER,
  LOCATION_ID     NUMBER,

  PRIMARY KEY (DEPARTNENT_ID),
  FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS (LOCATION_ID),
);

CREATE TABLE JOBS (
  JOB_ID     VARCHAR(10),
  JOB_TITLE  VARCHAR(35),
  MIN_SALARY NUMBER,
  MAX_SALARY NUMBER,

  PRIMARY KEY (JOB_ID),
);

CREATE TABLE JOB_HISTORY (
  EMPLOYEE_ID   NUMBER,
  START_DATE    DATE,
  END_DATE      DATE,
  JOB_ID        VARCHAR(10),
  DEPARTMENT_ID NUMBER,

  PRIMARY KEY (EMPLOYEE_ID, START_DATE),
  FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (DEPARTNENT_ID),
  FOREIGN KEY (JOB_ID) REFERENCES JOBS (JOB_ID),
);

CREATE TABLE EMPLOYEES (
  EMPLOYEE_ID    NUMBER,
  FIRST_NAME     VARCHAR(20),
  LAST_NAME      VARCHAR(25),
  EMAIL          VARCHAR(25),
  PHONE_NUMBER   VARCHAR(20),
  HIDE_DATE      DATE,
  JOB_ID         VARCHAR(10),
  SALARY         NUMBER,
  COMMISSION_PCT NUMBER,

  MANAGER_ID     NUMBER,
  DEPARTMENT_ID  NUMBER,

  PRIMARY KEY (EMPLOYEE_ID),
  FOREIGN KEY (MANAGER_ID) REFERENCES DEPARTMENTS (MANAGER_ID),
  FOREIGN KEY (DEPARTMENT_ID) REFERENCES JOB_HISTORY (DEPARTMENT_ID),
  FOREIGN KEY (JOB_ID) REFERENCES JOBS (JOB_ID),
);

CREATE TABLE JOB_GRADS (
  GRADE_LEVEL VARCHAR(2),
  LOWEST_SAL  NUMBER,
  HIGYEST_SAL NUMBER,
);