DROP TABLE  IF EXISTS SALESMAN;
DROP TABLE  IF EXISTS CUSTOMER;
DROP TABLE  IF EXISTS ORDERS;


CREATE TABLE SALESMAN (
  SALESMAN_ID numeric(5),
  NAME        varchar(30),
  CITY        varchar(15),
  COMMISSION  decimal(5, 2),
  PRIMARY KEY (SALESMAN_ID)
);

CREATE TABLE CUSTOMER (
  CUSTOMER_ID numeric(5),
  CUST_NAME   varchar(30),
  CITY        varchar(15),
  GRADE       numeric(3),
  SALESMAN_ID numeric(5),

  PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE ORDERS (
  ORD_NO      numeric(5),
  PURCH_AMT   decimal(8, 2),
  ORD_DATE    date,
  SALESMAN_ID numeric(5),
  CUSTOMER_ID numeric(5),

  PRIMARY KEY (ORD_NO),

  FOREIGN KEY (SALESMAN_ID) REFERENCES SALESMAN (SALESMAN_ID),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID),
);

INSERT INTO CUSTOMER (CUSTOMER_ID, CUST_NAME, CITY, GRADE)
VALUES ('1', 'Love VF', 'Goa', 1);

INSERT INTO CUSTOMER (CUSTOMER_ID, CUST_NAME, CITY, GRADE)
VALUES ('2', 'Lo V3', 'Azia', 1);

INSERT INTO SALESMAN (SALESMAN_ID, NAME, CITY, COMMISSION)
VALUES ('1', 'Lo V3', 'Duo', 5);

INSERT INTO SALESMAN (SALESMAN_ID, NAME, CITY, COMMISSION)
VALUES ('2', 'Lo V', 'Fia', 2);


SELECT
  CUST_NAME,
  CITY
FROM CUSTOMER;